# Generated by Django 5.1.4 on 2025-09-20 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Neutral', 'Neutral'), ('Other', 'Other')], default='Neutral', max_length=10)),
                ('journal_entry', models.TextField(blank=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entry_date')},
            },
        ),
    ]
